import Head from 'next/head'
import Home from '@/pages/Home'
import axios from 'axios'

export default function Index({ categoryList }) {
  return (
    <div>
      <Head>
        <title>Food Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home
        categoryList={categoryList}
      />
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`)
  return {
    props: {
      categoryList: res.data.data ? res.data.data : null,
    },
  }
}