import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'
import Head from 'next/head'
import Home from './Home'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Food Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  )
}
